### ISSUE TITLE
Questions About Test Data Generation code and 150-Degree Results

### ISSUE THREAD

**Issue by uigeunahn** [wustl-cig/DOLCE#7]
Hello,

I have a few questions regarding the test data provided:

Test Data Generation: Could you please provide the code for generating the test data, specifically the FBP and RLS images? Having access to this code would be extremely helpful for my analysis.

150-Degree Data: I noticed that data for the 150-degree is provided, so I ran the model with this data. It seems like the window level might have changed compared to other result of 60-degree, 90-degree, 120-degree as it seems little bit darker. Additionally, the performance for the 150-degree setup is similar to or slightly worse than the 120-degree configuration. Could you provide any insights or reasons why this might be happening? **Any suggestions for improving performance with not only 150-degree data but also less (ex 45-degree or 30-degree) degree would also be appreciated.**

Thank you for your work! I really learned a lot from your paper.

**Comment by hkimdavis** [comment]
The code to generate the test data used FBP and RLS functions in Livermore Tomography Tools (LTT) which requires a license. We released a python software package called LEAP as an open source, which provides forward projection, FBP, RLS, etc. You can find some examples of FBP and RLS using LEAP: GitHub.com/LLNL/LEAP.

**Comment by JiamingLiu-Jeremy** [comment]
Regarding the second question, there is no simple answer about the performance difference between 120 and 150 degrees, as it depends on the object configuration and the object shape/orientation with missing projection angles due to the limited angle setup. One potential limitation of the experiments is the fixed angular range, meaning the starting angle is always 0 degrees, resulting in an angular range of 0-150 degrees. Additionally, extreme LA settings are still a challenging issue, and we expect new conditional training of DPMs and sampling algorithms to help. We are working towards this direction.
